version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/tri-app

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - tri-app:/data/db

volumes:
  tri-app:

networks:
  tri-app:
    driver: bridge
